CAMPAIGN_GHOST_EDITOR_JSON_SCHEMA = {
    "name": "campaign_ghost_editor_output",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "action_summary",
            "changed_fields",
            "updated_campaign",
            "updated_asset_brief",
        ],
        "properties": {
            "action_summary": {"type": "string"},
            "changed_fields": {
                "type": "array",
                "minItems": 1,
                "maxItems": 12,
                "items": {"type": "string"},
            },
            "updated_campaign": {
                "type": "object",
                "additionalProperties": False,
                "required": [
                    "campaign_headline",
                    "campaign_angle",
                    "buyer_insight",
                    "caption",
                    "whatsapp_copy",
                    "offer_idea",
                    "story_flow",
                    "poster_direction",
                    "reel_direction",
                    "primary_cta",
                    "do_rules",
                    "avoid_rules",
                    "confidence",
                ],
                "properties": {
                    "campaign_headline": {"type": "string"},
                    "campaign_angle": {"type": "string"},
                    "buyer_insight": {"type": "string"},
                    "caption": {"type": "string"},
                    "whatsapp_copy": {"type": "string"},
                    "offer_idea": {"type": "string"},
                    "story_flow": {
                        "type": "array",
                        "minItems": 4,
                        "maxItems": 6,
                        "items": {"type": "string"},
                    },
                    "poster_direction": {"type": "string"},
                    "reel_direction": {"type": "string"},
                    "primary_cta": {"type": "string"},
                    "do_rules": {
                        "type": "array",
                        "minItems": 3,
                        "maxItems": 8,
                        "items": {"type": "string"},
                    },
                    "avoid_rules": {
                        "type": "array",
                        "minItems": 3,
                        "maxItems": 8,
                        "items": {"type": "string"},
                    },
                    "confidence": {"type": "number"},
                },
            },
            "updated_asset_brief": {
                "type": "object",
                "additionalProperties": False,
                "required": [
                    "creative_brief_title",
                    "poster_prompt",
                    "image_generation_prompt",
                    "poster_layout_direction",
                    "poster_text_hierarchy",
                    "poster_design_rules",
                    "reel_prompt",
                    "video_generation_prompt",
                    "reel_shot_list",
                    "reel_sound_direction",
                    "reel_editing_style",
                    "designer_notes",
                    "asset_risks",
                    "confidence",
                ],
                "properties": {
                    "creative_brief_title": {"type": "string"},
                    "poster_prompt": {"type": "string"},
                    "image_generation_prompt": {"type": "string"},
                    "poster_layout_direction": {"type": "string"},
                    "poster_text_hierarchy": {
                        "type": "array",
                        "minItems": 3,
                        "maxItems": 6,
                        "items": {"type": "string"},
                    },
                    "poster_design_rules": {
                        "type": "array",
                        "minItems": 3,
                        "maxItems": 8,
                        "items": {"type": "string"},
                    },
                    "reel_prompt": {"type": "string"},
                    "video_generation_prompt": {"type": "string"},
                    "reel_shot_list": {
                        "type": "array",
                        "minItems": 4,
                        "maxItems": 7,
                        "items": {"type": "string"},
                    },
                    "reel_sound_direction": {"type": "string"},
                    "reel_editing_style": {"type": "string"},
                    "designer_notes": {
                        "type": "array",
                        "minItems": 3,
                        "maxItems": 8,
                        "items": {"type": "string"},
                    },
                    "asset_risks": {
                        "type": "array",
                        "minItems": 0,
                        "maxItems": 6,
                        "items": {"type": "string"},
                    },
                    "confidence": {"type": "number"},
                },
            },
        },
    },
    "strict": True,
}
